### ISSUE TITLE
编译时提示'seccomp.h' file not found

### ISSUE THREAD

**Issue by airkid** [QingdaoU/Judger#1]
想学习一下这个项目down下来以后在
sudo python setup.py install 
时提示runner.c:5:10: fatal error: 'seccomp.h' file not found
不太明白这是什么，是否需要安装相关的依赖包？
操作系统是OSX

**Comment by virusdefender** [comment]
因为依赖seccomp的头文件。

但是并不清楚mac上怎么安装seccomp，虽然我也是在mac上写的代码，但是一直都是在linux下编译运行的。

linux需要 `apt-get install libseccomp-dev`

**Comment by airkid** [comment]
好的，我换linux试试，非常感谢。






在 2016-03-06 19:59:42，"李扬" <notifications@github.com> 写道：


因为依赖seccomp的头文件。

但是并不清楚mac上怎么安装seccomp，虽然我也是在mac上写的代码，但是一直都是在linux下编译运行的。

linux需要 apt-get install libseccomp-dev

**Comment by virusdefender** [comment]
对了，mac上限制内存也是无效的，因为mac上setrlimit没有实现这个功能。所以就用linux吧。
