### ISSUE TITLE
仅含Judger本体的Dockerfile？

### ISSUE THREAD

**Issue by Ray-Eldath** [QingdaoU/Judger#13]
**是否有一个仅含Judger本体、可以通过`_judger.run(...)`（Python）语句直接调用Judger的Docker呢？**

（我用自己编译的Judger执行[这里](http://docs.onlinejudge.me/Judger/English/#python-binding-python-27-and-35)的Python demo得到的echo.out文件是空的...而且每次把Windows下写的`.py`文件传到Linux服务器上调试感觉很不方便= =因此问一下有没有现成的；而[现有的docker-compose](https://github.com/QingdaoU/OnlineJudgeDeploy)中的judger是server，不能“直接调用”）

**Comment by virusdefender** [comment]
不好意思，才看到。

`docker run -it --rm registry.cn-hangzhou.aliyuncs.com/v-image/judge_server /bin/bash`

可以试试这个。

目前 deploy 中的 Judger 还是旧版的。

**Comment by virusdefender** [comment]
然后我新增了一个 demo 文件夹，如果你要自己修改代码编译的话，还可以增加`-v $PWD:/code`参数，直接把外边的代码映射进去。

**Comment by Ray-Eldath** [comment]
感谢！
已经解决。
