### ISSUE TITLE
用demo里的东西测试提示这个是为什么

### ISSUE THREAD

**Issue by ca110us** [QingdaoU/Judger#17]
edb@edb-X555LI:~/Judger/demo$ sudo python demo.py
Traceback (most recent call last):
  File "demo.py", line 26, in <module>
    gid=0)
ValueError: dlopen error

**Comment by virusdefender** [comment]
你需要先按照 http://docs.onlinejudge.me/Judger/English/ 的开头安装 judger 库

**Comment by ca110us** [comment]
sudo apt-get install libseccomp-dev吗 已经装了的

**Comment by ca110us** [comment]
可以了 请问real_time就是代码运行的时间吗？另外memory是kb为单位是吧

**Comment by ca110us** [comment]
cputime一直是0 realtime有时候1有时候0 做oj的话 那个才是运行时间

**Comment by zema1** [comment]
cputime

**Comment by ca110us** [comment]
那怎么是0ms啊 内存的单位是什么

**Comment by virusdefender** [comment]
代码跑的太快了，就是 0 

内存单位是字节
