### ISSUE TITLE
文档中是否有错误

### ISSUE THREAD

**Issue by MeiK2333** [QingdaoU/Judger#22]
https://docs.onlinejudge.me/#/judger/api?id=struct-result-members
- ```real_time```: actual running time of the process
- ```real_time```: max vaule of memory used by the processd
是不是写了两个 real_time ……

**Comment by virusdefender** [comment]
感谢，已经修正

https://github.com/QingdaoU/oj-docs/commit/56def609155140aed88cf4bb710d5508b4265240
