### ISSUE TITLE
对于不同语言（python2、3，java）给libjudger.so的参数应该是怎样的

### ISSUE THREAD

**Issue by wssssh** [QingdaoU/Judger#27]
在项目中似乎只有c语言的demo，在尝试python时我将python代码编译为main.pyc并chmod +x，demo.py中更改exe_path为main.pyc,将seccomp_rule_name设置为general，但这样仍然不能运行，
log显示：FATAL [2019-02-13 15:06:17] [/root/judger/Judger/src/child.c:159]Error: System errno: Exec format error; Internal errno: EXECVE_FAILED
请问python或java的参数应该怎样写才能正确运行

**Comment by virusdefender** [comment]
https://github.com/QingdaoU/OnlineJudge/blob/master/judge/languages.py#L99

**Comment by wssssh** [comment]
感谢回答！这里我有看到过，但仍然不知道https://github.com/QingdaoU/OnlineJudge/blob/f7bd9f16b44f944e0bb370dcc7e0e82a1f2b5eb4/judge/languages.py#L164
这个command是如何体现在libjudger.so的属性中。（在我的项目想只要直接使用libjudger.so）

**Comment by virusdefender** [comment]
你删了评论吧。。

看下 judge server 的代码
