### ISSUE TITLE
编译报错，demo中的main.c

### ISSUE THREAD

**Issue by wang-peijun** [QingdaoU/Judger#31]
命令`sudo /usr/lib/judger/libjudger.so --exe_path=/usr/bin/gcc --args=main.c --args=-o --args=main --input_path=1.in`
输出
<pre>collect2: fatal error: cannot find 'ld'
compilation terminated.
{
    "cpu_time": 10,
    "real_time": 19,
    "memory": 20480000,
    "signal": 0,
    "exit_code": 1,
    "error": 0,
    "result": 4
}
</pre>

**Comment by virusdefender** [comment]
加上 `--env PATH=$PATH`
