### ISSUE TITLE
Python writing file returns Runtime Error in File IO mode

### ISSUE THREAD

**Issue by XiChenn** [QingdaoU/Judger#39]
The "Signal" is 31 on the status page. I believe there is no file IO rule for Python (Java has the same problem)

**Comment by dianhsu** [comment]
I have the same problem in C language, and I solved this problem by add a seccomp rule `pread64`

**Comment by drabbit75** [comment]
why do you not commit to master branch for avoiding simular problems later

> I have the same problem in C language, and I solved this problem by add a seccomp rule `pread64`
