### ISSUE TITLE
php如何调用本项目

### ISSUE THREAD

**Issue by ty666** [QingdaoU/Judger#4]
本人最近在做一个在线考试的小应用。使用php写的，想请教一下如何使用php调用Judger。感谢。

**Comment by ty666** [comment]
作者: 请参考newnew分支文档

**Comment by virusdefender** [comment]
昨晚已经沟通过，目前并没有直接调用的办法，但是可以给出以下建议

 - 简单封装C语言版本或Python版本为命令行模式，然后php调用命令传递参数
 - 使用 https://github.com/QingdaoU/JudgeServer 项目，然后php和JudgeServer使用标准http通信，接收判题结果即可
