### ISSUE TITLE
Gives runtime error all time on Ubuntu 20.04

### ISSUE THREAD

**Issue by milon19** [QingdaoU/Judger#47]
I am trying to run the judger on ubuntu 20.04. It gives Run Time Error.

Result: 
{'cpu_time': 0, 'real_time': 155, 'memory': 1478656, 'signal': 31, 'exit_code': 0, 'error': 0, 'result': 4}

I am using python 3.8

**Comment by virusdefender** [comment]
Maybe the new version libc will use some extra syscall，run dmesg -T and give me the output.

**Comment by Cerulean0601** [comment]
I have same problem when I try to run demo.
The result of running `dmesg -T` :
`auid=1001 uid=0 gid=0 ses=62 pid=1559948 comm="main" exe="/home/<username>/Judger/demo/main" sig=31 arch=c000003e syscall=17 compat=0 ip=<ip> code=0x0`

**Comment by virusdefender** [comment]
You need to add syscall 17 to the white list
