### ISSUE TITLE
Ubuntu18.04中Java使用Process调用命令行执行有错误

### ISSUE THREAD

**Issue by HimitZH** [QingdaoU/Judger#50]
Python3和Python2的编译和跑测试点操作正常，
**Java调用沙盒编译正常，但是跑测试点一直RE，所有测试点的输出报错日志都是：Could not reserve enough space for code cache**

**C和C++编译一直失败，错误提示是：collect2: fatal error: cannot find 'ld'**

是不是无法用Java调用？我测试环境是Ubuntu18.04，程序不在docker容器里面的，g++ gcc openjdk-8都是正常用apt下载

**Comment by virusdefender** [comment]
- `Could not reserve enough space for code cache` Java 不要加内存限制 
 
```
--max_memory=<n>          Max Memory (byte)
--memory_limit_check_only=<n> only check memory usage, do not setrlimit (default False)
```

 - `ld` 的问题，记得把 PATH 环境变量传过去
