### ISSUE TITLE
测试时出现错误

### ISSUE THREAD

**Issue by f0rTwist** [QingdaoU/Judger#52]
OS: Ubuntu 20.04.2 LTS x86_64
Kernel: 5.4.0-58-generic
Judger version 2.1.1
2.7.18 (default, Aug  4 2020, 11:16:42) 
[GCC 9.3.0]

FAIL: test_writev (testcase.integration.test.IntegrationTest)**
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/twist/桌面/Judger-newnew/tests/Python_and_core/testcase/integration/test.py", line 329, in test_writev
    self.assertEqual(result["result"], _judger.RESULT_SUCCESS)
AssertionError: 4 != 0

----------------------------------------------------------------------
Ran 35 tests in 22.413s

FAILED (failures=1)

**Comment by virusdefender** [comment]
dmesg 看看是啥 syscall 的问题

**Comment by f0rTwist** [comment]
> dmesg 看看是啥 syscall 的问题

看了一下,是writev前面有个ls这里崩了...

[  363.743943] kauditd_printk_skb: 6 callbacks suppressed
[  363.743946] audit: type=1326 audit(1615568880.290:68): auid=1000 uid=0 gid=0 ses=2 pid=3627 comm="ls" exe="/usr/bin/ls" sig=31 arch=c000003e syscall=17 compat=0 ip=0x7f7de029b04e code=0x0
[  363.943213] stack[3640]: segfault at 7ffefc1b4830 ip 0000000000401cfc sp 00007ffefc1b4830 error 6 in stack[401000+94000]
[  363.943221] Code: e9 59 ff ff ff 66 0f 1f 84 00 00 00 00 00 e9 4b ff ff ff f3 0f 1e fa 55 48 89 e5 4c 8d 9c 24 00 00 00 fb 48 81 ec 00 10 00 00 <48> 83 0c 24 00 4c 39 dc 75 ef 48 83 ec 10 64 48 8b 04 25 28 00 00
[  364.522179] audit: type=1326 audit(1615568881.070:69): auid=1000 uid=0 gid=0 ses=2 pid=3673 comm="writev" exe="/tmp/integration/writev" sig=31 arch=c000003e syscall=17 compat=0 ip=0x7fabc9d7804e code=0x0

**Comment by f0rTwist** [comment]
在添加SCMP_SYS(pread64)进seccomp白名单后问题解决，感谢。

> > dmesg看看是啥syscall的问题
> 
> 看了一下，是writev前面有个ls这里崩溃了...
> 
> [363.743943] kauditd_printk_skb：抑制了6个回调
> [363.743946]审核：类型= 1326审核（1615568880.290：68）：auid = 1000 uid = 0 gid = 0 ses = 2 pid = 3627 comm =“ ls” exe =“ / usr / bin / ls“ sig = 31 arch = c000003e syscall = 17 compat = 0 ip = 0x7f7de029b04e code = 0x0
> [363.943213] stack [3640]：segfault at 7ffefc1b4830 ip 0000000000401cfc sp 00007ffefc1b4830 error 6 in stack [401000 + 94000]：
> [363。 e9 59 ff ff ff 66 0f 1f 84 00 00 00 00 00 e9 4b ff ff ff f3 0f 1e fa 55 48 89 e5 4c 8d 9c 24 00 00 00 fb 48 81 ec 00 10 00 00 <48> 83 0c 24 00 4c 39 dc 75 ef 48 83 ec 10 64 48 8b 04 25 28 00 00
> [364.522179]审核：类型= 1326审核（1615568881.070：69）：auid = 1000 uid = 0 gid = 0 ses = 2 pid = 3673 comm =“ writev “ exe =” / tmp / integration / writev“sig = 31 arch = c000003e syscall = 17 compat = 0 ip = 0x7fabc9d7804e code = 0x0
