### ISSUE TITLE
More CPU Time then allowed

### ISSUE THREAD

**Issue by rrutwik** [QingdaoU/Judger#53]
Submission is taking approx 900 to 1000 ms more than allowed CPU TIME, for all languages.(Tested with infinite loops)
Also, how can CPU time be less than real-time? Any suggestion on what could have gone wrong?
Correct Answer:- {'cpu_time': 89, 'real_time': 74, 'memory': 28536832, 'signal': 0, 'exit_code': 0, 'error': 0, 'result': 0}
Time Limit :- {'cpu_time': 1985, 'real_time': 1969, 'memory': 28913664, 'signal': 9, 'exit_code': 0, 'error': 0, 'result': 1}

**Comment by virusdefender** [comment]
https://github.com/QingdaoU/Judger/blob/newnew/src/child.c#L60

https://github.com/QingdaoU/Judger/blob/newnew/src/runner.c#L135

because `setrlimit` only supports second, so we should covert the limit to second ( for example: 100ms to 1s) and then check again at the end.

**Comment by virusdefender** [comment]
However, I don't fully understand your question, feel free to add comment in this issue.

**Comment by rrutwik** [comment]
So the parameter which I should pass in max_cpu_time should be in seconds?
Here:- https://github.com/QingdaoU/OnlineJudge/blob/6dda49592e511332d6893881c3091e6fcd25f42f/judge/dispatcher.py#L144 ?
