### ISSUE TITLE
如果你正在被设置seccomp所困扰

### ISSUE THREAD

**Issue by rainge-gcw** [QingdaoU/Judger#71]
即使没有任何内容，仅仅只有一个main函数和return,按照`c_cpp.c`中的代码设置好了限制，却发现依旧被kill
这可能是编译器版本或系统版本的原因，新的gcc版本可能会使用更加炫酷的内核函数
我的环境:
gcc version 11.3.0 (Ubuntu 11.3.0-1ubuntu1~22.04)
在我环境下的测试中，我发现对于下面这个简单cpp代码

```c++
#include<stdio.h>
int main(){
  int a;
  scanf("%d",&a);
  if(a==123)puts("yes");
  else puts("no");
  return 0;
}
```

我们需要额外允许newfstatat,lseek,rseq,getrandom,prlimit64,set_robust_list,openat,set_tid_address 这几个系统调用
我并不清楚开放这些后是否能保证系统不被恶意代码攻击
此外，如果即使开发了这些系统调用后，你的程序依旧被kill,那么你可以尝试使用trace来检查demo.cpp到底调用了哪些函数。

如果你认为trace很复杂，你也可以打开

```
/usr/include/x86_64-linux-gnu/asm/unistd_64.h
```

来获取所有的内核函数名并将其全部加载到代码中，接着使用二分的方法逐步检查出到底是哪些系统调用

很耗时但也很稳妥

**Comment by mikucat0309** [comment]
Fixed in #79
