### ISSUE TITLE
关于内存限制的问题

### ISSUE THREAD

**Issue by FlyingOnion** [QingdaoU/Judger#8]
你好，我想问下child.c 45行
`max_memory.rlim_cur = max_memory.rlim_max = (rlim_t) (_config->max_memory) * 2;`
乘2是什么原因？

**Comment by virusdefender** [comment]
因为有时候限制内存太小的话，进程可能启动都有问题，所以可以使用的内存限制大一些，最后超内存是按照实际获取到的用量数字来的。

**Comment by FlyingOnion** [comment]
我自己也写了一个类似的，用hello world测试，显示子进程的ru_maxrss是444KB，但rlimit至少要设置4MB才能运行，否则会报`a.out: error while loading shared libraries: libc.so.6: failed to map segment from shared object: Cannot allocate memory`，这是正常的情况吗？

**Comment by virusdefender** [comment]
@FlyingOnion 因为 `maxrss` 不算动态库之类的内存吧，而 `rlimit_as` 太小的话，可能会影响进程初始化和库的加载。

> RSS is the Resident Set Size and is used to show how much memory is allocated to that process and is in RAM. It does not include memory that is swapped out. It does include memory from shared libraries as long as the pages from those libraries are actually in memory. It does include all stack and heap memory.
